import 'app_en.dart';

final Map<String, String> te = {
  ...en,
  'tagline': 'అన్ని కొబ్బరి కార్యకలాపాలు',
  'transactions': 'లావాదేవీలు',
  'reports': 'నివేదికలు',
  'active_branch': 'ప్రస్తుత బ్రాంచ్',
  'language': 'భాష',
  'synced': 'సింక్ అయింది',
  'sync_pending': 'సింక్ కోసం వేచి ఉంది',
  'role_workspace': 'పాత్ర పని స్థలం',
  'search': 'లావాదేవీ, పార్టీ లేదా వౌచర్ వెతకండి',
  'filter': 'వడపోత',
  'create_entry': 'కొత్త నమోదు',
  'new_entry': 'కొత్త నమోదు',
  'recent_entries': 'ఇటీవలి నమోదులు',
  'details': 'వివరాలు',
  'today': 'ఈ రోజు',
  'entries': 'నమోదులు',
  'total_value': 'మొత్తం విలువ',
  'this_branch': 'ఈ బ్రాంచ్',
  'next': 'తర్వాత',
  'back': 'వెనుకకు',
  'save': 'నిర్ధారించి సేవ్ చేయండి',
  'save_draft': 'డ్రాఫ్ట్ సేవ్',
  'retry': 'మళ్లీ ప్రయత్నించండి',
  'refresh': 'రిఫ్రెష్',
  'export': 'ఎగుమతి',
  'share': 'షేర్',
  'duplicate': 'నకలు చేయండి',
  'optional': 'ఐచ్ఛికం',
  'required_field': 'ఈ వివరము అవసరం',
  'invalid_number': 'సరైన సంఖ్య నమోదు చేయండి',
  'invalid_mobile': 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
  'nothing_here': 'ఇంకా డేటా లేదు',
  'nothing_here_hint': 'సేవ్ చేసిన నమోదులు ఇక్కడ కనిపిస్తాయి.',
  'something_went_wrong': 'ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.',
  'network_error':
      'సర్వర్‌ను చేరుకోలేకపోయాం. మీ పని ఆఫ్‌లైన్‌లో సేవ్ అవుతుంది.',
  'session_expired': 'మీ సెషన్ ముగిసింది.',
  'loading': 'లోడ్ అవుతోంది…',
  'step': 'దశ',
  'of': 'లో',
  'status': 'స్థితి',
  'date': 'తేదీ',
  'amount': 'మొత్తం',
  'estimated_total': 'అంచనా మొత్తం',
  'transaction_saved': 'లావాదేవీ సేవ్ అయింది',
  'saved_offline_detail': 'పరికరంలో సేవ్ అయి సింక్ కోసం వేచి ఉంది.',
  'saved_synced_detail': 'విజయవంతంగా సేవ్ చేసి సింక్ అయింది.',
  'view_entries': 'నమోదులు చూడండి',
  'discount_safe': 'డిస్కౌంట్ నిర్ణీత పరిమితిలో ఉంది',
  'approval_required': 'మేనేజర్ ఆమోదం మరియు సమాచారం అవసరం',
  'per_thousand_pieces': 'ప్రతి 1,000 పీసులకు',
  'per_hundred_kg': 'ప్రతి 100 కిలోలకు',
  'notify_above': 'దీనికి పైగా తెలియజేయండి',
  'maximum': 'గరిష్ఠం',
  'calculated_labour_payment': 'లెక్కించిన కార్మిక చెల్లింపు',
  'review_empty': 'మీరు నమోదు చేసిన వివరాలు ఇక్కడ కనిపిస్తాయి.',
  'select_account': 'ఖాతా ఎంచుకోండి',
  'report_summary': 'నివేదిక సారాంశం',
  'net_profit': 'నికర లాభం',
  'report_copied': 'నివేదిక సారాంశం కాపీ అయింది.',
  'ready_to_share': 'షేర్ చేయడానికి సిద్ధం.',
  'this_month': 'ఈ నెల',
  'last_90_days': '90 రోజులు',
  'all_time': 'మొత్తం కాలం',
  'open_live_report': 'లైవ్ నివేదిక తెరవండి',
  'transaction_scope': 'ఈ పాత్రకు అందుబాటులో ఉన్న లావాదేవీలు',
  'transaction_card_hint': 'బ్రాంచ్ లావాదేవీలను నమోదు చేసి తనిఖీ చేయండి',
  'reports_subtitle':
      'బ్రాంచ్ రిజిస్టర్లు, ఖాతాలు, పంపిణీ మరియు లాభ నివేదికలు.',
  'finance_manager_role': 'ఫైనాన్స్ మేనేజర్',
  'warehouse_manager_role': 'గిడ్డంగి మేనేజర్',
  'procurement_manager_role': 'కొనుగోలు మేనేజర్',
  'sales_manager_role': 'సేల్స్ మేనేజర్',
  'transaction_purchaseOrder': 'కొనుగోలు ఆర్డర్',
  'transaction_purchaseInvoice': 'కొనుగోలు బిల్లు',
  'transaction_sales': 'అమ్మకాలు',
  'transaction_loadingDispatch': 'లోడింగ్ & పంపిణీ',
  'transaction_customerReceipt': 'కస్టమర్ రసీదు',
  'transaction_supplierPayment': 'సరఫరాదారు చెల్లింపు',
  'transaction_cashBankExpense': 'నగదు & బ్యాంక్ ఖర్చు',
  'transaction_labourPayment': 'కార్మిక చెల్లింపు',
  'transaction_bagPurchase': 'సంచి కొనుగోలు',
  'report_purchaseRegister': 'కొనుగోలు రిజిస్టర్',
  'report_salesRegister': 'అమ్మకాల రిజిస్టర్',
  'report_supplierStatement': 'సరఫరాదారు ఖాతా',
  'report_customerStatement': 'కస్టమర్ ఖాతా',
  'report_labourAttendance': 'కార్మికుల హాజరు',
  'report_pendingDispatch': 'పెండింగ్ పంపిణీ',
  'report_outstanding': 'బకాయిలు',
  'report_profitLoss': 'లాభ నష్టం',
  'review_title': 'తనిఖీ చేసి సేవ్ చేయండి',
  'review_help': 'సేవ్ చేయడానికి ముందు అన్ని వివరాలను తనిఖీ చేయండి.',
  'party_title': 'పార్టీ మరియు బ్రాంచ్',
  'party_help': 'పార్టీ మరియు సంబంధిత బ్రాంచ్‌ను ఎంచుకోండి.',
  'quantity_title': 'పరిమాణం మరియు ధర',
  'quantity_help': 'పరిమాణం మరియు నిర్ణయించిన ధరను నమోదు చేయండి.',
  'discount_help':
      'డిస్కౌంట్ తర్వాత అసలు పరిమాణం ఆటోమేటిక్‌గా లెక్కించబడుతుంది.',
  'mode_title': 'లెక్కింపు విధానం',
  'mode_help': 'టన్నేజ్, పీస్ లేదా లెస్సింగ్ ఎంచుకోండి.',
  'charges_title': 'అదనపు ఛార్జీలు',
  'charges_help': 'వర్తించే ఛార్జీలు జోడించి మిగతావి సున్నాగా ఉంచండి.',
  'vehicle_title': 'వాహనం మరియు కస్టమర్',
  'vehicle_help': 'లోడింగ్‌కు ముందు వాహనం మరియు డ్రైవర్ వివరాలు నమోదు చేయండి.',
  'load_title': 'లోడ్ వివరాలు',
  'load_help': 'స్టాక్, నింపే బరువు మరియు పరిమాణం ఎంచుకోండి.',
  'receipt_help': 'ఇన్వాయిస్ వారీగా లేదా మొత్తం రసీదు ఎంచుకోండి.',
  'payment_title': 'చెల్లింపు వివరాలు',
  'payment_help': 'చెల్లింపు విధానం మరియు మొత్తాన్ని నమోదు చేయండి.',
  'expense_title': 'ఖర్చు వర్గీకరణ',
  'expense_help': 'నగదు లేదా బ్యాంక్ నమోదును వర్గీకరించండి.',
  'worker_title': 'కార్మికుడి వివరాలు',
  'worker_help': 'శాశ్వత లేదా తాత్కాలిక కార్మికుడిని ఎంచుకోండి.',
  'wages_title': 'ఓవర్‌టైమ్ మరియు లోడింగ్',
  'wages_help': 'ఉదయం OT, సాయంత్రం OT మరియు లోడింగ్ ఆటోమేటిక్‌గా కలుస్తాయి.',
  'field_branch': 'బ్రాంచ్',
  'field_supplier': 'సరఫరాదారు',
  'field_customer': 'కస్టమర్',
  'field_warehouse': 'గిడ్డంగి',
  'field_invoiceNumber': 'ఇన్వాయిస్ నంబర్',
  'field_orderNumber': 'ఆర్డర్ నంబర్',
  'field_invoiceAllocation': 'కేటాయింపు విధానం',
  'field_invoice': 'ఇన్వాయిస్',
  'field_item': 'కొబ్బరి / వస్తువు',
  'field_quantityMode': 'పరిమాణ విధానం',
  'field_quantity': 'పరిమాణం',
  'field_discount': 'లెస్సింగ్ / డిస్కౌంట్',
  'field_actualQuantity': 'చెల్లించవలసిన పరిమాణం',
  'field_purchaseRate': 'కొనుగోలు ధర',
  'field_salesRate': 'అమ్మకపు ధర',
  'field_loadingCharge': 'లోడింగ్ ఛార్జీ',
  'field_marketCess': 'మార్కెట్ సెస్',
  'field_bagStickCharge': 'సంచి మరియు కుట్టు',
  'field_freight': 'రవాణా',
  'field_paymentMode': 'చెల్లింపు విధానం',
  'field_amount': 'మొత్తం',
  'field_vehicleNumber': 'వాహనం నంబర్',
  'field_driverName': 'డ్రైవర్ పేరు',
  'field_driverMobile': 'డ్రైవర్ మొబైల్',
  'field_bagType': 'సంచి రకం',
  'field_fillingWeight': 'నింపే బరువు',
  'field_workerType': 'కార్మికుడి రకం',
  'field_labour': 'శాశ్వత కార్మికుడు',
  'field_temporaryWorkerName': 'తాత్కాలిక కార్మికుడి పేరు',
  'field_morningOt': 'ఉదయం OT గంటలు',
  'field_eveningOt': 'సాయంత్రం OT గంటలు',
  'field_otRate': 'OT ధర',
  'field_transactionKind': 'నమోదు రకం',
  'field_expenseHead': 'ఖర్చు శీర్షిక',
  'field_description': 'వివరణ',
  'option_tonnage': 'టన్నుల వారీగా',
  'option_piece_wise': 'పీసుల వారీగా',
  'option_lessing_ton_wise': 'లెస్సింగ్ · టన్నుల వారీగా',
  'option_lessing_piece_wise': 'లెస్సింగ్ · పీసుల వారీగా',
  'option_invoice_by_invoice': 'ఇన్వాయిస్ వారీగా',
  'option_cumulative': 'మొత్తంగా',
  'option_cash': 'నగదు',
  'option_bank': 'బ్యాంక్',
  'option_expense': 'ఖర్చు',
  'option_other_income': 'ఇతర ఆదాయం',
  'option_permanent': 'శాశ్వత',
  'option_temporary': 'తాత్కాలిక',
  'metric_total_sales': 'మొత్తం అమ్మకాలు',
  'metric_purchases_cogs': 'కొనుగోళ్లు / అమ్మకాల వ్యయం',
  'metric_gross_profit': 'స్థూల లాభం',
  'metric_operating_expenses': 'నిర్వహణ ఖర్చులు',
  'metric_other_income': 'ఇతర ఆదాయం',
  'net_margin': 'నికర మార్జిన్',
};
