import 'app_en.dart';

final Map<String, String> kn = {
  ...en,
  'tagline': 'ಎಲ್ಲಾ ತೆಂಗಿನಕಾಯಿ ಕಾರ್ಯಾಚರಣೆಗಳು',
  'transactions': 'ವಹಿವಾಟುಗಳು',
  'reports': 'ವರದಿಗಳು',
  'active_branch': 'ಸಕ್ರಿಯ ಬ್ರಾಂಚ್',
  'language': 'ಭಾಷೆ',
  'synced': 'ಸಿಂಕ್ ಆಗಿದೆ',
  'sync_pending': 'ಸಿಂಕ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
  'role_workspace': 'ಪಾತ್ರ ಕಾರ್ಯಸ್ಥಳ',
  'search': 'ವಹಿವಾಟು, ಪಾರ್ಟಿ ಅಥವಾ ವೋಚರ್ ಹುಡುಕಿ',
  'filter': 'ಫಿಲ್ಟರ್',
  'create_entry': 'ಹೊಸ ದಾಖಲೆ',
  'new_entry': 'ಹೊಸ ದಾಖಲೆ',
  'recent_entries': 'ಇತ್ತೀಚಿನ ದಾಖಲೆಗಳು',
  'details': 'ವಿವರಗಳು',
  'today': 'ಇಂದು',
  'entries': 'ದಾಖಲೆಗಳು',
  'total_value': 'ಒಟ್ಟು ಮೌಲ್ಯ',
  'this_branch': 'ಈ ಬ್ರಾಂಚ್',
  'next': 'ಮುಂದೆ',
  'back': 'ಹಿಂದೆ',
  'save': 'ದೃಢೀಕರಿಸಿ ಉಳಿಸಿ',
  'save_draft': 'ಕರಡು ಉಳಿಸಿ',
  'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  'refresh': 'ರಿಫ್ರೆಶ್',
  'export': 'ರಫ್ತು',
  'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
  'duplicate': 'ನಕಲು ಮಾಡಿ',
  'optional': 'ಐಚ್ಛಿಕ',
  'required_field': 'ಈ ವಿವರ ಅಗತ್ಯ',
  'invalid_number': 'ಸರಿಯಾದ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'invalid_mobile': 'ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'nothing_here': 'ಇನ್ನೂ ಡೇಟಾ ಇಲ್ಲ',
  'nothing_here_hint': 'ಉಳಿಸಿದ ದಾಖಲೆಗಳು ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.',
  'something_went_wrong': 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  'network_error':
      'ಸರ್ವರ್ ಸಂಪರ್ಕ ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ನಿಮ್ಮ ಕೆಲಸ ಸಾಧನದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ.',
  'session_expired': 'ನಿಮ್ಮ ಸೆಷನ್ ಮುಗಿದಿದೆ.',
  'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
  'step': 'ಹಂತ',
  'of': 'ರಲ್ಲಿ',
  'status': 'ಸ್ಥಿತಿ',
  'date': 'ದಿನಾಂಕ',
  'amount': 'ಮೊತ್ತ',
  'estimated_total': 'ಅಂದಾಜು ಒಟ್ಟು',
  'transaction_saved': 'ವಹಿವಾಟು ಉಳಿಸಲಾಗಿದೆ',
  'saved_offline_detail': 'ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ಸಿಂಕ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ.',
  'saved_synced_detail': 'ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಿ ಸಿಂಕ್ ಮಾಡಲಾಗಿದೆ.',
  'view_entries': 'ದಾಖಲೆಗಳನ್ನು ನೋಡಿ',
  'discount_safe': 'ರಿಯಾಯಿತಿ ನಿಗದಿತ ಮಿತಿಯೊಳಗೆ ಇದೆ',
  'approval_required': 'ವ್ಯವಸ್ಥಾಪಕ ಅನುಮೋದನೆ ಮತ್ತು ಸೂಚನೆ ಅಗತ್ಯ',
  'per_thousand_pieces': 'ಪ್ರತಿ 1,000 ಪೀಸ್‌ಗೆ',
  'per_hundred_kg': 'ಪ್ರತಿ 100 ಕೆಜಿಗೆ',
  'notify_above': 'ಇದಕ್ಕಿಂತ ಮೇಲೆ ತಿಳಿಸಿ',
  'maximum': 'ಗರಿಷ್ಠ',
  'calculated_labour_payment': 'ಲೆಕ್ಕಿಸಿದ ಕಾರ್ಮಿಕ ಪಾವತಿ',
  'review_empty': 'ನೀವು ನಮೂದಿಸಿದ ವಿವರಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
  'select_account': 'ಖಾತೆ ಆಯ್ಕೆಮಾಡಿ',
  'report_summary': 'ವರದಿ ಸಾರಾಂಶ',
  'net_profit': 'ನಿವ್ವಳ ಲಾಭ',
  'report_copied': 'ವರದಿ ಸಾರಾಂಶ ನಕಲಾಗಿದೆ.',
  'ready_to_share': 'ಹಂಚಲು ಸಿದ್ಧವಾಗಿದೆ.',
  'this_month': 'ಈ ತಿಂಗಳು',
  'last_90_days': '90 ದಿನಗಳು',
  'all_time': 'ಎಲ್ಲಾ ಸಮಯ',
  'open_live_report': 'ಲೈವ್ ವರದಿ ತೆರೆಯಿರಿ',
  'transaction_scope': 'ಈ ಪಾತ್ರಕ್ಕೆ ಲಭ್ಯವಿರುವ ವಹಿವಾಟುಗಳು',
  'transaction_card_hint': 'ಬ್ರಾಂಚ್ ವಹಿವಾಟುಗಳನ್ನು ದಾಖಲಿಸಿ ಪರಿಶೀಲಿಸಿ',
  'reports_subtitle':
      'ಬ್ರಾಂಚ್ ರಿಜಿಸ್ಟರ್‌ಗಳು, ಸ್ಟೇಟ್‌ಮೆಂಟ್‌ಗಳು, ರವಾನೆ ಮತ್ತು ಲಾಭ.',
  'finance_manager_role': 'ಹಣಕಾಸು ವ್ಯವಸ್ಥಾಪಕ',
  'warehouse_manager_role': 'ಗೋದಾಮು ವ್ಯವಸ್ಥಾಪಕ',
  'procurement_manager_role': 'ಖರೀದಿ ವ್ಯವಸ್ಥಾಪಕ',
  'sales_manager_role': 'ಮಾರಾಟ ವ್ಯವಸ್ಥಾಪಕ',
  'transaction_purchaseOrder': 'ಖರೀದಿ ಆದೇಶ',
  'transaction_purchaseInvoice': 'ಖರೀದಿ ಇನ್ವಾಯ್ಸ್',
  'transaction_sales': 'ಮಾರಾಟ',
  'transaction_loadingDispatch': 'ಲೋಡಿಂಗ್ & ರವಾನೆ',
  'transaction_customerReceipt': 'ಗ್ರಾಹಕ ರಸೀದಿ',
  'transaction_supplierPayment': 'ಪೂರೈಕೆದಾರ ಪಾವತಿ',
  'transaction_cashBankExpense': 'ನಗದು & ಬ್ಯಾಂಕ್ ವೆಚ್ಚ',
  'transaction_labourPayment': 'ಕಾರ್ಮಿಕ ಪಾವತಿ',
  'transaction_bagPurchase': 'ಚೀಲ ಖರೀದಿ',
  'report_purchaseRegister': 'ಖರೀದಿ ರಿಜಿಸ್ಟರ್',
  'report_salesRegister': 'ಮಾರಾಟ ರಿಜಿಸ್ಟರ್',
  'report_supplierStatement': 'ಪೂರೈಕೆದಾರ ಸ್ಟೇಟ್‌ಮೆಂಟ್',
  'report_customerStatement': 'ಗ್ರಾಹಕ ಸ್ಟೇಟ್‌ಮೆಂಟ್',
  'report_labourAttendance': 'ಕಾರ್ಮಿಕ ಹಾಜರಿ',
  'report_pendingDispatch': 'ಬಾಕಿ ರವಾನೆ',
  'report_outstanding': 'ಬಾಕಿ',
  'report_profitLoss': 'ಲಾಭ ಮತ್ತು ನಷ್ಟ',
  'review_title': 'ಪರಿಶೀಲಿಸಿ ಉಳಿಸಿ',
  'review_help': 'ಉಳಿಸುವ ಮೊದಲು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
  'party_title': 'ಪಾರ್ಟಿ ಮತ್ತು ಶಾಖೆ',
  'party_help': 'ಪಾರ್ಟಿ ಮತ್ತು ಸಂಬಂಧಿತ ಶಾಖೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
  'quantity_title': 'ಪ್ರಮಾಣ ಮತ್ತು ದರ',
  'quantity_help': 'ಪ್ರಮಾಣ ಮತ್ತು ಒಪ್ಪಿದ ದರ ನಮೂದಿಸಿ.',
  'discount_help': 'ರಿಯಾಯಿತಿ ನಂತರ ನಿಜವಾದ ಪ್ರಮಾಣ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಲೆಕ್ಕವಾಗುತ್ತದೆ.',
  'mode_title': 'ಲೆಕ್ಕಿಸುವ ವಿಧಾನ',
  'mode_help': 'ಟನ್ನೇಜ್, ಪೀಸ್ ಅಥವಾ ಲೆಸ್ಸಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ.',
  'charges_title': 'ಹೆಚ್ಚುವರಿ ಶುಲ್ಕಗಳು',
  'charges_help': 'ಅನ್ವಯಿಸುವ ಶುಲ್ಕ ಸೇರಿಸಿ, ಉಳಿದವು ಶೂನ್ಯವಾಗಿರಲಿ.',
  'vehicle_title': 'ವಾಹನ ಮತ್ತು ಗ್ರಾಹಕ',
  'vehicle_help': 'ಲೋಡಿಂಗ್ ಮೊದಲು ವಾಹನ ಮತ್ತು ಚಾಲಕ ವಿವರ ನಮೂದಿಸಿ.',
  'load_title': 'ಲೋಡ್ ವಿವರಗಳು',
  'load_help': 'ಸ್ಟಾಕ್, ತುಂಬುವ ತೂಕ ಮತ್ತು ಪ್ರಮಾಣ ಆಯ್ಕೆಮಾಡಿ.',
  'receipt_help': 'ಇನ್ವಾಯ್ಸ್ ಪ್ರಕಾರ ಅಥವಾ ಒಟ್ಟು ರಸೀದಿ ಆಯ್ಕೆಮಾಡಿ.',
  'payment_title': 'ಪಾವತಿ ವಿವರಗಳು',
  'payment_help': 'ಪಾವತಿ ವಿಧಾನ ಮತ್ತು ಮೊತ್ತ ನಮೂದಿಸಿ.',
  'expense_title': 'ವೆಚ್ಚ ವರ್ಗೀಕರಣ',
  'expense_help': 'ನಗದು ಅಥವಾ ಬ್ಯಾಂಕ್ ದಾಖಲೆಯನ್ನು ವರ್ಗೀಕರಿಸಿ.',
  'worker_title': 'ಕಾರ್ಮಿಕ ವಿವರಗಳು',
  'worker_help': 'ಶಾಶ್ವತ ಅಥವಾ ತಾತ್ಕಾಲಿಕ ಕಾರ್ಮಿಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
  'wages_title': 'ಓವರ್‌ಟೈಮ್ ಮತ್ತು ಲೋಡಿಂಗ್',
  'wages_help': 'ಬೆಳಿಗ್ಗೆ OT, ಸಂಜೆ OT ಮತ್ತು ಲೋಡಿಂಗ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸೇರುತ್ತವೆ.',
  'field_branch': 'ಬ್ರಾಂಚ್',
  'field_supplier': 'ಪೂರೈಕೆದಾರ',
  'field_customer': 'ಗ್ರಾಹಕ',
  'field_warehouse': 'ಗೋದಾಮು',
  'field_invoiceNumber': 'ಇನ್ವಾಯ್ಸ್ ಸಂಖ್ಯೆ',
  'field_orderNumber': 'ಆರ್ಡರ್ ಸಂಖ್ಯೆ',
  'field_invoiceAllocation': 'ಹಂಚಿಕೆ ವಿಧಾನ',
  'field_invoice': 'ಇನ್ವಾಯ್ಸ್',
  'field_item': 'ತೆಂಗಿನಕಾಯಿ / ವಸ್ತು',
  'field_quantityMode': 'ಪ್ರಮಾಣ ವಿಧಾನ',
  'field_quantity': 'ಪ್ರಮಾಣ',
  'field_discount': 'ಲೆಸ್ಸಿಂಗ್ / ರಿಯಾಯಿತಿ',
  'field_actualQuantity': 'ಪಾವತಿಸಬೇಕಾದ ಪ್ರಮಾಣ',
  'field_purchaseRate': 'ಖರೀದಿ ದರ',
  'field_salesRate': 'ಮಾರಾಟ ದರ',
  'field_loadingCharge': 'ಲೋಡಿಂಗ್ ಶುಲ್ಕ',
  'field_marketCess': 'ಮಾರುಕಟ್ಟೆ ಸೆಸ್',
  'field_bagStickCharge': 'ಚೀಲ ಮತ್ತು ಹೊಲಿಗೆ',
  'field_freight': 'ಸಾಗಣೆ',
  'field_paymentMode': 'ಪಾವತಿ ವಿಧಾನ',
  'field_amount': 'ಮೊತ್ತ',
  'field_vehicleNumber': 'ವಾಹನ ಸಂಖ್ಯೆ',
  'field_driverName': 'ಚಾಲಕ ಹೆಸರು',
  'field_driverMobile': 'ಚಾಲಕ ಮೊಬೈಲ್',
  'field_bagType': 'ಚೀಲದ ವಿಧ',
  'field_fillingWeight': 'ತುಂಬುವ ತೂಕ',
  'field_workerType': 'ಕಾರ್ಮಿಕ ವಿಧ',
  'field_labour': 'ಶಾಶ್ವತ ಕಾರ್ಮಿಕ',
  'field_temporaryWorkerName': 'ತಾತ್ಕಾಲಿಕ ಕಾರ್ಮಿಕ ಹೆಸರು',
  'field_morningOt': 'ಬೆಳಿಗ್ಗೆ OT ಗಂಟೆಗಳು',
  'field_eveningOt': 'ಸಂಜೆ OT ಗಂಟೆಗಳು',
  'field_otRate': 'OT ದರ',
  'field_transactionKind': 'ದಾಖಲೆ ವಿಧ',
  'field_expenseHead': 'ವೆಚ್ಚ ಶೀರ್ಷಿಕೆ',
  'field_description': 'ವಿವರಣೆ',
  'option_tonnage': 'ಟನ್ ಪ್ರಕಾರ',
  'option_piece_wise': 'ಪೀಸ್ ಪ್ರಕಾರ',
  'option_lessing_ton_wise': 'ಲೆಸಿಂಗ್ · ಟನ್ ಪ್ರಕಾರ',
  'option_lessing_piece_wise': 'ಲೆಸಿಂಗ್ · ಪೀಸ್ ಪ್ರಕಾರ',
  'option_invoice_by_invoice': 'ಇನ್ವಾಯ್ಸ್ ಪ್ರಕಾರ',
  'option_cumulative': 'ಒಟ್ಟಾಗಿ',
  'option_cash': 'ನಗದು',
  'option_bank': 'ಬ್ಯಾಂಕ್',
  'option_expense': 'ವೆಚ್ಚ',
  'option_other_income': 'ಇತರೆ ಆದಾಯ',
  'option_permanent': 'ಶಾಶ್ವತ',
  'option_temporary': 'ತಾತ್ಕಾಲಿಕ',
  'metric_total_sales': 'ಒಟ್ಟು ಮಾರಾಟ',
  'metric_purchases_cogs': 'ಖರೀದಿ / ಮಾರಾಟ ವೆಚ್ಚ',
  'metric_gross_profit': 'ಒಟ್ಟು ಲಾಭ',
  'metric_operating_expenses': 'ಕಾರ್ಯಾಚರಣೆ ವೆಚ್ಚಗಳು',
  'metric_other_income': 'ಇತರೆ ಆದಾಯ',
  'net_margin': 'ನಿವ್ವಳ ಮಾರ್ಜಿನ್',
};
