import 'app_en.dart';

final Map<String, String> hi = {
  ...en,
  'tagline': 'नारियल के सभी कार्य',
  'transactions': 'लेन-देन',
  'reports': 'रिपोर्ट',
  'active_branch': 'सक्रिय ब्रांच',
  'language': 'भाषा',
  'synced': 'सिंक हो गया',
  'sync_pending': 'सिंक की प्रतीक्षा',
  'role_workspace': 'भूमिका कार्यक्षेत्र',
  'search': 'लेन-देन, पार्टी या वाउचर खोजें',
  'filter': 'फ़िल्टर',
  'create_entry': 'नई प्रविष्टि',
  'new_entry': 'नई प्रविष्टि',
  'recent_entries': 'हाल की प्रविष्टियाँ',
  'details': 'विवरण',
  'today': 'आज',
  'entries': 'प्रविष्टियाँ',
  'total_value': 'कुल मूल्य',
  'this_branch': 'इस ब्रांच में',
  'next': 'आगे',
  'back': 'पीछे',
  'save': 'पुष्टि करके सेव करें',
  'save_draft': 'ड्राफ्ट सेव करें',
  'retry': 'फिर कोशिश करें',
  'refresh': 'रीफ़्रेश',
  'export': 'निर्यात',
  'share': 'शेयर',
  'duplicate': 'प्रतिलिपि बनाएँ',
  'optional': 'वैकल्पिक',
  'required_field': 'यह जानकारी आवश्यक है',
  'invalid_number': 'सही संख्या दर्ज करें',
  'invalid_mobile': 'सही 10 अंकों का मोबाइल नंबर दर्ज करें',
  'nothing_here': 'अभी कोई डेटा नहीं',
  'nothing_here_hint': 'सेव किए गए रिकॉर्ड यहाँ दिखाई देंगे।',
  'something_went_wrong': 'कुछ गलत हुआ। फिर कोशिश करें।',
  'network_error': 'सर्वर उपलब्ध नहीं है। आपका काम ऑफ़लाइन सेव हो सकता है।',
  'session_expired': 'आपका सत्र समाप्त हो गया है।',
  'loading': 'लोड हो रहा है…',
  'step': 'चरण',
  'of': 'में से',
  'status': 'स्थिति',
  'date': 'तारीख',
  'amount': 'राशि',
  'estimated_total': 'अनुमानित कुल',
  'transaction_saved': 'लेन-देन सेव हो गया',
  'saved_offline_detail': 'डिवाइस पर सेव है और सिंक की प्रतीक्षा में है।',
  'saved_synced_detail': 'सफलतापूर्वक सेव और सिंक हो गया।',
  'view_entries': 'प्रविष्टियाँ देखें',
  'discount_safe': 'छूट तय सीमा के भीतर है',
  'approval_required': 'मैनेजर मंज़ूरी और सूचना आवश्यक',
  'per_thousand_pieces': 'प्रति 1,000 पीस',
  'per_hundred_kg': 'प्रति 100 किलो',
  'notify_above': 'इससे अधिक पर सूचना',
  'maximum': 'अधिकतम',
  'calculated_labour_payment': 'गणना किया गया मज़दूर भुगतान',
  'review_empty': 'आपके दर्ज किए गए विवरण यहाँ दिखेंगे।',
  'select_account': 'खाता चुनें',
  'report_summary': 'रिपोर्ट सारांश',
  'net_profit': 'शुद्ध लाभ',
  'report_copied': 'रिपोर्ट सारांश कॉपी हो गया।',
  'ready_to_share': 'शेयर करने के लिए तैयार।',
  'this_month': 'इस महीने',
  'last_90_days': '90 दिन',
  'all_time': 'सभी समय',
  'open_live_report': 'लाइव रिपोर्ट खोलें',
  'transaction_scope': 'इस भूमिका के लिए उपलब्ध लेन-देन',
  'transaction_card_hint': 'ब्रांच के लेन-देन बनाएँ और जाँचें',
  'reports_subtitle': 'ब्रांच रजिस्टर, स्टेटमेंट, डिस्पैच और लाभ की रिपोर्ट।',
  'finance_manager_role': 'वित्त प्रबंधक',
  'warehouse_manager_role': 'गोदाम प्रबंधक',
  'procurement_manager_role': 'खरीद प्रबंधक',
  'sales_manager_role': 'बिक्री प्रबंधक',
  'transaction_purchaseOrder': 'खरीद आदेश',
  'transaction_purchaseInvoice': 'खरीद बिल',
  'transaction_sales': 'बिक्री',
  'transaction_loadingDispatch': 'लोडिंग और भेजना',
  'transaction_customerReceipt': 'ग्राहक रसीद',
  'transaction_supplierPayment': 'सप्लायर भुगतान',
  'transaction_cashBankExpense': 'कैश और बैंक खर्च',
  'transaction_labourPayment': 'मज़दूर भुगतान',
  'transaction_bagPurchase': 'बैग खरीद',
  'report_purchaseRegister': 'खरीद रजिस्टर',
  'report_salesRegister': 'बिक्री रजिस्टर',
  'report_supplierStatement': 'सप्लायर स्टेटमेंट',
  'report_customerStatement': 'ग्राहक स्टेटमेंट',
  'report_labourAttendance': 'मज़दूर उपस्थिति',
  'report_pendingDispatch': 'लंबित भेजना',
  'report_outstanding': 'बकाया',
  'report_profitLoss': 'लाभ और हानि',
  'review_title': 'जाँचें और सेव करें',
  'review_help': 'सेव करने से पहले सभी विवरण जाँचें।',
  'party_title': 'पार्टी और ब्रांच',
  'party_help': 'पार्टी और संबंधित ब्रांच चुनें।',
  'quantity_title': 'मात्रा और दर',
  'quantity_help': 'मात्रा और तय दर दर्ज करें।',
  'discount_help': 'छूट के बाद असली मात्रा अपने-आप निकलेगी।',
  'mode_title': 'गणना का तरीका',
  'mode_help': 'टन, पीस या लेसिंग चुनें।',
  'charges_title': 'अतिरिक्त शुल्क',
  'charges_help': 'लागू शुल्क जोड़ें, बाकी शून्य रखें।',
  'vehicle_title': 'वाहन और ग्राहक',
  'vehicle_help': 'लोडिंग से पहले वाहन और ड्राइवर दर्ज करें।',
  'load_title': 'लोड विवरण',
  'load_help': 'स्टॉक, भरती और मात्रा चुनें।',
  'receipt_help': 'इनवॉइस अनुसार या कुल रसीद चुनें।',
  'payment_title': 'भुगतान विवरण',
  'payment_help': 'भुगतान तरीका और राशि दर्ज करें।',
  'expense_title': 'खर्च वर्गीकरण',
  'expense_help': 'कैश या बैंक प्रविष्टि को वर्गीकृत करें।',
  'worker_title': 'मज़दूर विवरण',
  'worker_help': 'स्थायी या अस्थायी मज़दूर चुनें।',
  'wages_title': 'ओवरटाइम और लोडिंग',
  'wages_help': 'सुबह OT, शाम OT और लोडिंग अपने-आप जुड़ेंगे।',
  'field_branch': 'ब्रांच',
  'field_supplier': 'सप्लायर',
  'field_customer': 'ग्राहक',
  'field_warehouse': 'गोदाम',
  'field_invoiceNumber': 'इनवॉइस नंबर',
  'field_orderNumber': 'ऑर्डर नंबर',
  'field_invoiceAllocation': 'वितरण तरीका',
  'field_invoice': 'इनवॉइस',
  'field_item': 'नारियल / वस्तु',
  'field_quantityMode': 'मात्रा तरीका',
  'field_quantity': 'मात्रा',
  'field_discount': 'लेसिंग / छूट',
  'field_actualQuantity': 'देय मात्रा',
  'field_purchaseRate': 'खरीद दर',
  'field_salesRate': 'बिक्री दर',
  'field_loadingCharge': 'लोडिंग शुल्क',
  'field_marketCess': 'मार्केट सेस',
  'field_bagStickCharge': 'बैग और सिलाई',
  'field_freight': 'माल भाड़ा',
  'field_paymentMode': 'भुगतान तरीका',
  'field_amount': 'राशि',
  'field_vehicleNumber': 'वाहन नंबर',
  'field_driverName': 'ड्राइवर नाम',
  'field_driverMobile': 'ड्राइवर मोबाइल',
  'field_bagType': 'बैग प्रकार',
  'field_fillingWeight': 'भरती वजन',
  'field_workerType': 'मज़दूर प्रकार',
  'field_labour': 'स्थायी मज़दूर',
  'field_temporaryWorkerName': 'अस्थायी मज़दूर नाम',
  'field_morningOt': 'सुबह OT घंटे',
  'field_eveningOt': 'शाम OT घंटे',
  'field_otRate': 'OT दर',
  'field_transactionKind': 'प्रविष्टि प्रकार',
  'field_expenseHead': 'खर्च मद',
  'field_description': 'विवरण',
  'option_tonnage': 'टन के अनुसार',
  'option_piece_wise': 'पीस के अनुसार',
  'option_lessing_ton_wise': 'लेसिंग · टन के अनुसार',
  'option_lessing_piece_wise': 'लेसिंग · पीस के अनुसार',
  'option_invoice_by_invoice': 'इनवॉइस के अनुसार',
  'option_cumulative': 'कुल मिलाकर',
  'option_cash': 'नकद',
  'option_bank': 'बैंक',
  'option_expense': 'खर्च',
  'option_other_income': 'अन्य आय',
  'option_permanent': 'स्थायी',
  'option_temporary': 'अस्थायी',
  'metric_total_sales': 'कुल बिक्री',
  'metric_purchases_cogs': 'खरीद / बिक्री लागत',
  'metric_gross_profit': 'सकल लाभ',
  'metric_operating_expenses': 'संचालन खर्च',
  'metric_other_income': 'अन्य आय',
  'net_margin': 'शुद्ध मार्जिन',
};
