const Map<String, String> en = {
  'app_name': 'COCOPER',
  'tagline': 'All coconut operations',
  'transactions': 'Transactions',
  'reports': 'Reports',
  'active_branch': 'Active branch',
  'language': 'Language',
  'synced': 'Synced',
  'sync_pending': 'Waiting to sync',
  'role_workspace': 'Role workspace',
  'search': 'Search transaction, party or voucher',
  'filter': 'Filter',
  'create_entry': 'Create entry',
  'new_entry': 'New entry',
  'recent_entries': 'Recent entries',
  'details': 'Details',
  'today': 'Today',
  'entries': 'entries',
  'total_value': 'Total value',
  'this_branch': 'this branch',
  'next': 'Next',
  'back': 'Back',
  'save': 'Confirm & save',
  'save_draft': 'Save draft',
  'retry': 'Try again',
  'refresh': 'Refresh',
  'export': 'Export',
  'share': 'Share',
  'duplicate': 'Duplicate',
  'optional': 'Optional',
  'required_field': 'This field is required',
  'invalid_number': 'Enter a valid number',
  'invalid_mobile': 'Enter a valid 10-digit mobile number',
  'nothing_here': 'Nothing here yet',
  'nothing_here_hint': 'New records will appear here after they are saved.',
  'something_went_wrong': 'Something went wrong. Please try again.',
  'network_error':
      'Unable to reach the server. Your work can be saved offline.',
  'session_expired': 'Your session has expired.',
  'loading': 'Loading…',
  'step': 'Step',
  'of': 'of',
  'status': 'Status',
  'date': 'Date',
  'amount': 'Amount',
  'estimated_total': 'Estimated total',
  'transaction_saved': 'Transaction saved',
  'saved_offline_detail': 'Saved on this device and waiting to sync.',
  'saved_synced_detail': 'Saved and synced successfully.',
  'view_entries': 'View entries',
  'discount_safe': 'Within configured discount limit',
  'approval_required': 'Manager approval and notification required',
  'per_thousand_pieces': 'Per 1,000 pieces',
  'per_hundred_kg': 'Per 100 kg',
  'notify_above': 'notify above',
  'maximum': 'maximum',
  'calculated_labour_payment': 'Calculated labour payment',
  'review_empty': 'Your entered details will appear here.',
  'select_account': 'Select account',
  'report_summary': 'Report summary',
  'net_profit': 'Net profit',
  'report_copied': 'Report summary copied.',
  'ready_to_share': 'Ready to share.',
  'this_month': 'This month',
  'last_90_days': '90 days',
  'all_time': 'All time',
  'open_live_report': 'Open live report',
  'transaction_scope': 'Transactions available for this role',
  'transaction_card_hint': 'Create and review branch transactions',
  'reports_subtitle':
      'Branch registers, statements, dispatch and profitability.',
  'finance_manager_role': 'Finance Manager',
  'warehouse_manager_role': 'Warehouse Manager',
  'procurement_manager_role': 'Procurement Manager',
  'sales_manager_role': 'Sales Manager',
  'transaction_purchaseOrder': 'Purchase Order',
  'transaction_purchaseInvoice': 'Purchase Invoice',
  'transaction_sales': 'Sales',
  'transaction_loadingDispatch': 'Loading & Dispatch',
  'transaction_customerReceipt': 'Customer Receipt',
  'transaction_supplierPayment': 'Supplier Payment',
  'transaction_cashBankExpense': 'Cash & Bank Expense',
  'transaction_labourPayment': 'Labour Payment',
  'transaction_bagPurchase': 'Bag Purchase',
  'report_purchaseRegister': 'Purchase Register',
  'report_salesRegister': 'Sales Register',
  'report_supplierStatement': 'Supplier Statement',
  'report_customerStatement': 'Customer Statement',
  'report_labourAttendance': 'Labour Attendance',
  'report_pendingDispatch': 'Pending Dispatch',
  'report_outstanding': 'Outstanding',
  'report_profitLoss': 'Profit & Loss',
  'review_title': 'Review and save',
  'review_help': 'Check every detail before saving this transaction.',
  'party_title': 'Party and branch',
  'party_help': 'Select the party and where this transaction belongs.',
  'quantity_title': 'Quantity and rate',
  'quantity_help': 'Enter the coconut or bag quantity and agreed rate.',
  'discount_help':
      'The payable quantity is calculated automatically after discount.',
  'mode_title': 'Calculation method',
  'mode_help': 'Choose tonnage, piece-wise or lessing before adding quantity.',
  'charges_title': 'Additional charges',
  'charges_help': 'Add applicable charges. Leave unused charges as zero.',
  'vehicle_title': 'Vehicle and customer',
  'vehicle_help': 'Capture the vehicle and driver before loading.',
  'load_title': 'Load details',
  'load_help': 'Select stock, filling weight and quantity to dispatch.',
  'receipt_help': 'Choose invoice-wise allocation or a cumulative receipt.',
  'payment_title': 'Payment details',
  'payment_help':
      'Choose payment method and enter the received or paid amount.',
  'expense_title': 'Expense classification',
  'expense_help': 'Classify this branch cash or bank entry.',
  'worker_title': 'Worker details',
  'worker_help': 'Choose one permanent or temporary worker.',
  'wages_title': 'Overtime and loading',
  'wages_help':
      'Morning OT, evening OT and loading are totalled automatically.',
  'field_branch': 'Branch',
  'field_supplier': 'Supplier',
  'field_customer': 'Customer',
  'field_warehouse': 'Warehouse',
  'field_invoiceNumber': 'Invoice number',
  'field_orderNumber': 'Order number',
  'field_invoiceAllocation': 'Allocation method',
  'field_invoice': 'Invoice',
  'field_item': 'Coconut / item',
  'field_quantityMode': 'Quantity method',
  'field_quantity': 'Quantity',
  'field_discount': 'Lessing / discount',
  'field_actualQuantity': 'Payable quantity',
  'field_purchaseRate': 'Purchase rate',
  'field_salesRate': 'Sales rate',
  'field_loadingCharge': 'Loading charge',
  'field_marketCess': 'Market cess',
  'field_bagStickCharge': 'Bag and stitching',
  'field_freight': 'Freight',
  'field_paymentMode': 'Payment mode',
  'field_amount': 'Amount',
  'field_vehicleNumber': 'Vehicle number',
  'field_driverName': 'Driver name',
  'field_driverMobile': 'Driver mobile',
  'field_bagType': 'Bag type',
  'field_fillingWeight': 'Filling weight',
  'field_workerType': 'Worker type',
  'field_labour': 'Permanent labour',
  'field_temporaryWorkerName': 'Temporary worker name',
  'field_morningOt': 'Morning OT hours',
  'field_eveningOt': 'Evening OT hours',
  'field_otRate': 'OT rate',
  'field_transactionKind': 'Entry type',
  'field_expenseHead': 'Expense head',
  'field_description': 'Description',
  'option_tonnage': 'Tonnage',
  'option_piece_wise': 'Piece wise',
  'option_lessing_ton_wise': 'Lessing · Ton wise',
  'option_lessing_piece_wise': 'Lessing · Piece wise',
  'option_invoice_by_invoice': 'Invoice by invoice',
  'option_cumulative': 'Cumulative',
  'option_cash': 'Cash',
  'option_bank': 'Bank',
  'option_upi': 'UPI',
  'option_expense': 'Expense',
  'option_other_income': 'Other income',
  'option_permanent': 'Permanent',
  'option_temporary': 'Temporary',
  'metric_total_sales': 'Total sales',
  'metric_purchases_cogs': 'Purchases / COGS',
  'metric_gross_profit': 'Gross profit',
  'metric_operating_expenses': 'Operating expenses',
  'metric_other_income': 'Other income',
  'net_margin': 'net margin',
};
