import 'app_en.dart';

final Map<String, String> ta = {
  ...en,
  'tagline': 'அனைத்து தேங்காய் செயல்பாடுகள்',
  'transactions': 'பரிவர்த்தனைகள்',
  'reports': 'அறிக்கைகள்',
  'active_branch': 'செயலில் உள்ள கிளை',
  'language': 'மொழி',
  'synced': 'ஒத்திசைந்தது',
  'sync_pending': 'ஒத்திசைக்க காத்திருக்கிறது',
  'role_workspace': 'பங்கு பணியிடம்',
  'search': 'பரிவர்த்தனை, நிறுவனம் அல்லது வவுச்சரைத் தேடுங்கள்',
  'filter': 'வடிகட்டி',
  'create_entry': 'புதிய பதிவு',
  'new_entry': 'புதிய பதிவு',
  'recent_entries': 'சமீபத்திய பதிவுகள்',
  'details': 'விவரங்கள்',
  'today': 'இன்று',
  'entries': 'பதிவுகள்',
  'total_value': 'மொத்த மதிப்பு',
  'this_branch': 'இந்தக் கிளை',
  'next': 'அடுத்து',
  'back': 'பின்',
  'save': 'உறுதிசெய்து சேமி',
  'save_draft': 'வரைவை சேமி',
  'retry': 'மீண்டும் முயலவும்',
  'refresh': 'புதுப்பி',
  'export': 'ஏற்றுமதி',
  'share': 'பகிர்',
  'duplicate': 'நகலெடுக்கவும்',
  'optional': 'விருப்பம்',
  'required_field': 'இந்த விவரம் தேவை',
  'invalid_number': 'சரியான எண்ணை உள்ளிடவும்',
  'invalid_mobile': 'சரியான 10 இலக்க கைபேசி எண்ணை உள்ளிடவும்',
  'nothing_here': 'தரவு இல்லை',
  'nothing_here_hint': 'சேமித்த பதிவுகள் இங்கே காணப்படும்.',
  'something_went_wrong': 'ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயலவும்.',
  'network_error':
      'சேவையகத்தை அணுக முடியவில்லை. உங்கள் பணி சாதனத்தில் சேமிக்கப்படும்.',
  'session_expired': 'உங்கள் அமர்வு முடிந்தது.',
  'loading': 'ஏற்றுகிறது…',
  'step': 'படி',
  'of': 'இல்',
  'status': 'நிலை',
  'date': 'தேதி',
  'amount': 'தொகை',
  'estimated_total': 'மதிப்பிடப்பட்ட மொத்தம்',
  'transaction_saved': 'பரிவர்த்தனை சேமிக்கப்பட்டது',
  'saved_offline_detail':
      'சாதனத்தில் சேமிக்கப்பட்டு ஒத்திசைக்க காத்திருக்கிறது.',
  'saved_synced_detail': 'வெற்றிகரமாக சேமித்து ஒத்திசைக்கப்பட்டது.',
  'view_entries': 'பதிவுகளைக் காண்க',
  'discount_safe': 'தள்ளுபடி நிர்ணயிக்கப்பட்ட வரம்பில் உள்ளது',
  'approval_required': 'மேலாளர் ஒப்புதல் மற்றும் அறிவிப்பு தேவை',
  'per_thousand_pieces': '1,000 எண்ணிக்கைக்கு',
  'per_hundred_kg': '100 கிலோவுக்கு',
  'notify_above': 'இதற்கு மேல் அறிவிக்கவும்',
  'maximum': 'அதிகபட்சம்',
  'calculated_labour_payment': 'கணக்கிடப்பட்ட தொழிலாளர் பணம்',
  'review_empty': 'நீங்கள் உள்ளிட்ட விவரங்கள் இங்கே தோன்றும்.',
  'select_account': 'கணக்கைத் தேர்ந்தெடுக்கவும்',
  'report_summary': 'அறிக்கை சுருக்கம்',
  'net_profit': 'நிகர லாபம்',
  'report_copied': 'அறிக்கை சுருக்கம் நகலெடுக்கப்பட்டது.',
  'ready_to_share': 'பகிரத் தயார்.',
  'this_month': 'இந்த மாதம்',
  'last_90_days': '90 நாட்கள்',
  'all_time': 'அனைத்தும்',
  'open_live_report': 'நேரடி அறிக்கையைத் திறக்கவும்',
  'transaction_scope': 'இந்தப் பங்கிற்கு கிடைக்கும் பரிவர்த்தனைகள்',
  'transaction_card_hint': 'கிளை பரிவர்த்தனைகளை உருவாக்கி சரிபார்க்கவும்',
  'reports_subtitle': 'கிளை பதிவுகள், அறிக்கைகள், அனுப்புதல் மற்றும் லாபம்.',
  'finance_manager_role': 'நிதி மேலாளர்',
  'warehouse_manager_role': 'கிடங்கு மேலாளர்',
  'procurement_manager_role': 'கொள்முதல் மேலாளர்',
  'sales_manager_role': 'விற்பனை மேலாளர்',
  'transaction_purchaseOrder': 'கொள்முதல் ஆணை',
  'transaction_purchaseInvoice': 'கொள்முதல் விலைப்பட்டியல்',
  'transaction_sales': 'விற்பனை',
  'transaction_loadingDispatch': 'ஏற்றுதல் & அனுப்புதல்',
  'transaction_customerReceipt': 'வாடிக்கையாளர் ரசீது',
  'transaction_supplierPayment': 'சப்ளையர் பணம்',
  'transaction_cashBankExpense': 'பணம் & வங்கி செலவு',
  'transaction_labourPayment': 'தொழிலாளர் பணம்',
  'transaction_bagPurchase': 'பை கொள்முதல்',
  'report_purchaseRegister': 'கொள்முதல் பதிவு',
  'report_salesRegister': 'விற்பனை பதிவு',
  'report_supplierStatement': 'சப்ளையர் அறிக்கை',
  'report_customerStatement': 'வாடிக்கையாளர் அறிக்கை',
  'report_labourAttendance': 'தொழிலாளர் வருகை',
  'report_pendingDispatch': 'நிலுவை அனுப்புதல்',
  'report_outstanding': 'நிலுவை',
  'report_profitLoss': 'லாப நஷ்டம்',
  'review_title': 'சரிபார்த்து சேமிக்கவும்',
  'review_help': 'சேமிப்பதற்கு முன் அனைத்து விவரங்களையும் சரிபார்க்கவும்.',
  'party_title': 'நிறுவனம் மற்றும் கிளை',
  'party_help': 'நிறுவனத்தையும் தொடர்புடைய கிளையையும் தேர்ந்தெடுக்கவும்.',
  'quantity_title': 'அளவு மற்றும் விலை',
  'quantity_help': 'அளவையும் ஒப்புக்கொண்ட விலையையும் உள்ளிடவும்.',
  'discount_help': 'தள்ளுபடிக்குப் பிறகு உண்மை அளவு தானாக கணக்கிடப்படும்.',
  'mode_title': 'கணக்கீட்டு முறை',
  'mode_help': 'டன், எண்ணிக்கை அல்லது லெஸ்ஸிங் முறையைத் தேர்ந்தெடுக்கவும்.',
  'charges_title': 'கூடுதல் கட்டணங்கள்',
  'charges_help':
      'பொருந்தும் கட்டணங்களைச் சேர்த்து மற்றவற்றை பூஜ்யமாக விடவும்.',
  'vehicle_title': 'வாகனம் மற்றும் வாடிக்கையாளர்',
  'vehicle_help':
      'ஏற்றுவதற்கு முன் வாகனம் மற்றும் ஓட்டுநர் விவரங்களை உள்ளிடவும்.',
  'load_title': 'சுமை விவரங்கள்',
  'load_help': 'இருப்பு, நிரப்பு எடை மற்றும் அளவைத் தேர்ந்தெடுக்கவும்.',
  'receipt_help':
      'விலைப்பட்டியல் வாரியாக அல்லது மொத்த ரசீதைத் தேர்ந்தெடுக்கவும்.',
  'payment_title': 'பணம் விவரங்கள்',
  'payment_help': 'பணம் செலுத்தும் முறையையும் தொகையையும் உள்ளிடவும்.',
  'expense_title': 'செலவு வகை',
  'expense_help': 'பணம் அல்லது வங்கி பதிவை வகைப்படுத்தவும்.',
  'worker_title': 'தொழிலாளர் விவரங்கள்',
  'worker_help': 'நிரந்தர அல்லது தற்காலிக தொழிலாளரைத் தேர்ந்தெடுக்கவும்.',
  'wages_title': 'கூடுதல் நேரம் மற்றும் ஏற்றுதல்',
  'wages_help': 'காலை OT, மாலை OT மற்றும் ஏற்றுதல் தானாகக் கூட்டப்படும்.',
  'field_branch': 'கிளை',
  'field_supplier': 'சப்ளையர்',
  'field_customer': 'வாடிக்கையாளர்',
  'field_warehouse': 'கிடங்கு',
  'field_invoiceNumber': 'விலைப்பட்டியல் எண்',
  'field_orderNumber': 'ஆணை எண்',
  'field_invoiceAllocation': 'ஒதுக்கீட்டு முறை',
  'field_invoice': 'விலைப்பட்டியல்',
  'field_item': 'தேங்காய் / பொருள்',
  'field_quantityMode': 'அளவு முறை',
  'field_quantity': 'அளவு',
  'field_discount': 'லெஸ்ஸிங் / தள்ளுபடி',
  'field_actualQuantity': 'செலுத்த வேண்டிய அளவு',
  'field_purchaseRate': 'கொள்முதல் விலை',
  'field_salesRate': 'விற்பனை விலை',
  'field_loadingCharge': 'ஏற்றுதல் கட்டணம்',
  'field_marketCess': 'சந்தை வரி',
  'field_bagStickCharge': 'பை மற்றும் தையல்',
  'field_freight': 'சரக்கு கட்டணம்',
  'field_paymentMode': 'பணம் செலுத்தும் முறை',
  'field_amount': 'தொகை',
  'field_vehicleNumber': 'வாகன எண்',
  'field_driverName': 'ஓட்டுநர் பெயர்',
  'field_driverMobile': 'ஓட்டுநர் கைபேசி',
  'field_bagType': 'பை வகை',
  'field_fillingWeight': 'நிரப்பு எடை',
  'field_workerType': 'தொழிலாளர் வகை',
  'field_labour': 'நிரந்தர தொழிலாளர்',
  'field_temporaryWorkerName': 'தற்காலிக தொழிலாளர் பெயர்',
  'field_morningOt': 'காலை OT மணி',
  'field_eveningOt': 'மாலை OT மணி',
  'field_otRate': 'OT விலை',
  'field_transactionKind': 'பதிவு வகை',
  'field_expenseHead': 'செலவுத் தலைப்பு',
  'field_description': 'விளக்கம்',
  'option_tonnage': 'டன் வாரியாக',
  'option_piece_wise': 'எண்ணிக்கை வாரியாக',
  'option_lessing_ton_wise': 'லெசிங் · டன் வாரியாக',
  'option_lessing_piece_wise': 'லெசிங் · எண்ணிக்கை வாரியாக',
  'option_invoice_by_invoice': 'விலைப்பட்டியல் வாரியாக',
  'option_cumulative': 'மொத்தமாக',
  'option_cash': 'பணம்',
  'option_bank': 'வங்கி',
  'option_expense': 'செலவு',
  'option_other_income': 'பிற வருமானம்',
  'option_permanent': 'நிரந்தரம்',
  'option_temporary': 'தற்காலிகம்',
  'metric_total_sales': 'மொத்த விற்பனை',
  'metric_purchases_cogs': 'கொள்முதல் / விற்பனைச் செலவு',
  'metric_gross_profit': 'மொத்த லாபம்',
  'metric_operating_expenses': 'செயல்பாட்டு செலவுகள்',
  'metric_other_income': 'பிற வருமானம்',
  'net_margin': 'நிகர விளிம்பு',
};
